Settings
PrinzPizza42/DeathMinigames pull request #40
Opened 2024-10-07 15:52 UTC by PrinzPizza42

settings added and changed handling of config

2024-10-07 16:23 UTC, JonasFranke requested changes
Overall good but I found some stuff for you to fix

2024-10-07 16:23 UTC, JonasFranke commented on src/main/java/org/example/DeathMinigames/commands/GameCMD.java
> +        Difficulty difficulty = new Difficulty();
You can use static methods for small stuff like this :)

2024-10-07 16:23 UTC, JonasFranke commented on src/main/java/org/example/DeathMinigames/deathMinigames/Main.java
> +    private void cloneConfigToHasMap() {
The config methods should probably life in their own class. Your Main is pretty bloated

2024-10-07 16:23 UTC, JonasFranke commented on src/main/java/org/example/DeathMinigames/listeners/ChatListener.java
>              /*if (event.getMessage().equalsIgnoreCase("/game start")) {
Can be removed

2024-10-07 16:23 UTC, JonasFranke commented on src/main/java/org/example/DeathMinigames/listeners/InventoryListener.java
> +        if(event.getView().getTitle().equals("Settings")) {
Inventories shouldn't be compared by their titles. Use PDC https://docs.papermc.io/paper/dev/pdc

2024-10-07 16:23 UTC, JonasFranke commented on src/main/java/org/example/DeathMinigames/minigames/JumpAndRun.java
>                          case 0:
Not from this PR, but switch case can be collapsed as shown here https://stackoverflow.com/questions/5086322/java-switch-statement-multiple-cases

2024-10-07 16:23 UTC, JonasFranke commented on src/main/java/org/example/DeathMinigames/minigames/Minigame.java
> +            player.sendTitle("§6Du hast verloren", "§6Dein Inventar wird an deinen Todesort (" + "§cX:" + deaths.get(player.getUniqueId()).getBlockX() + " §cY: " + deaths.get(player.getUniqueId()).ge
Components

2024-10-07 16:23 UTC, JonasFranke commented on src/main/java/org/example/DeathMinigames/settings/MainMenu.java
> +            case"2":
ints can be used directly as cases. No need to convert them to String
```suggestion
switch (slotClicked) {
            case 0:
                introduction.showInventory(player);
                break;
            case 1:
                difficulty.showInventory(player);
                break;
            case 2:
```

2024-10-07 16:23 UTC, JonasFranke commented on src/main/java/org/example/DeathMinigames/listeners/InventoryListener.java
> +                playerClicked = getPlayerFromWhitelistFromSpecificInt(i);
When closing the inv (i guess). This error is thrown:
```
java.lang.IndexOutOfBoundsException: Index -999 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100) ~[?:?]
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106) ~[?:?]
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302) ~[?:?]
	at java.base/java.util.Objects.checkIndex(Objects.java:385) ~[?:?]
	at java.base/java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
	at DeathMinigames-1.0-SNAPSHOT.jar/org.example.DeathMinigames.listeners.InventoryListener.getPlayerFromWhitelistFromSpecificInt(InventoryListener.java:102) ~[DeathMinigames-1.0-SNAPSHOT.jar:?]
	at DeathMinigames-1.0-SNAPSHOT.jar/org.example.DeathMinigames.listeners.InventoryListener.onSettingsClick(InventoryListener.java:74) ~[DeathMinigames-1.0-SNAPSHOT.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor22.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-119-7cd4f2c]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3224) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:69) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:33) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1535) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1512) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1505) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
	at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1464) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1471) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1316) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
```

2024-10-07 16:25 UTC, JonasFranke reviewed
![Screenshot From 2024-10-07 18-19-47](https://github.com/user-attachments/assets/fefa7c10-7cda-4f07-9dac-6ca0cf1b3a6b)

On my machine, I couldn't see anything inside the SubSetting invs

2024-10-07 16:31 UTC, PrinzPizza42 commented on src/main/java/org/example/DeathMinigames/listeners/InventoryListener.java
> +                playerClicked = getPlayerFromWhitelistFromSpecificInt(i);
This and the following problem you comment is happening because the plugin is getting all players from the whitelist. I made it that way, because on our server we are only working with players on our whitelist. Because you have no whitelist, it isnt getting any players from it

2024-10-07 17:26 UTC, JonasFranke commented on src/main/java/org/example/DeathMinigames/listeners/InventoryListener.java
> +                playerClicked = getPlayerFromWhitelistFromSpecificInt(i);
It shouldn't throw an error anyway. You can surround it with try catch

2024-10-07 19:16 UTC, PrinzPizza42 commented on src/main/java/org/example/DeathMinigames/listeners/InventoryListener.java
> +                playerClicked = getPlayerFromWhitelistFromSpecificInt(i);
I could try to generate my own list of players who already played on the server, would that be alright?

2024-10-07 19:37 UTC, PrinzPizza42 commented on src/main/java/org/example/DeathMinigames/listeners/InventoryListener.java
> +                playerClicked = getPlayerFromWhitelistFromSpecificInt(i);
i would do that with just getting every player who joins the server and isnt already on a ArrayList and putting him into the ArrayList and also into a list in the config. I would then just use this list instead of the whitelist

2024-10-07 19:39 UTC, PrinzPizza42 commented on src/main/java/org/example/DeathMinigames/listeners/InventoryListener.java
> +        if(event.getView().getTitle().equals("Settings")) {
i will replace my current system with that tomorrow or the day after tomorrow

2024-10-08 08:25 UTC, JonasFranke commented on src/main/java/org/example/DeathMinigames/listeners/InventoryListener.java
> +                playerClicked = getPlayerFromWhitelistFromSpecificInt(i);
I believe Bukkit#getServer()#getOfflinePlayers() does that for you

2024-10-08 08:33 UTC, JonasFranke commented on src/main/java/org/example/DeathMinigames/commands/GameCMD.java
> +        Difficulty difficulty = new Difficulty();
The listener and the Main class

2024-10-08 08:34 UTC, JonasFranke commented on src/main/java/org/example/DeathMinigames/minigames/Difficulty.java
> +    public void PlayerPay(Player player) {
```suggestion
    public void playerPay(Player player) {
```

2024-10-08 08:35 UTC, JonasFranke commented on src/main/java/org/example/DeathMinigames/commands/GameCMD.java
> +                            difficulty.PlayerPay(player);
```suggestion
                            difficulty.playerPay(player);
```

2024-10-09 13:24 UTC, PrinzPizza42 commented on src/main/java/org/example/DeathMinigames/commands/GameCMD.java
> +        Difficulty difficulty = new Difficulty();
if i try to change the listener to static it tells me, that it cant be static. Personally i wouldnt chagne anything here, because it is working perfectly fine

2024-10-09 13:28 UTC, PrinzPizza42 commented on src/main/java/org/example/DeathMinigames/listeners/InventoryListener.java
> +        if(event.getView().getTitle().equals("Settings")) {
i just looked at the article and as i understand it, you cant add a pdc to an inventory, only to chunks, worlds, Entitys, TileStates, ItemMeta and Structure.

2024-10-09 13:32 UTC, PrinzPizza42 commented on src/main/java/org/example/DeathMinigames/listeners/InventoryListener.java
> +        if(event.getView().getTitle().equals("Settings")) {
It seems like for Inventory you should be using InventoryHolders instead

2024-10-09 13:32 UTC, PrinzPizza42 commented on src/main/java/org/example/DeathMinigames/listeners/InventoryListener.java
> +        if(event.getView().getTitle().equals("Settings")) {
https://docs.papermc.io/paper/dev/custom-inventory-holder

2024-10-10 20:55 UTC, merged