Settings-SetUp
PrinzPizza42/DeathMinigames pull request #58
Opened 2024-10-21 13:32 UTC by PrinzPizza42

2024-10-21 14:04 UTC, JonasFranke submitted a review, later dismissed

2024-10-21 14:04 UTC, JonasFranke commented on src/main/resources/translations.json
> +      "test": "Dies ist ein test %s",
Can be removed

```suggestion
```

2024-10-21 14:04 UTC, JonasFranke commented on src/main/resources/translations.json
> +      "changedDiff1": "Deine Schwierigkeit wurde um 1 auf ",
String templates should be used
```suggestion
      "changedDiff": "Deine Schwierigkeit wurde um 1 auf %s erhöht",
```

In the class the used strings can be simply added behind a comma. (→ See main plugin)

2024-10-21 14:04 UTC, JonasFranke commented on src/main/resources/translations.json
> +      "changedDiff2": " erhöht",
Therefore, this can be removed
```suggestion
```

2024-10-21 14:04 UTC, JonasFranke commented on src/main/resources/translations.json
> +      "setDiffTo1": "Deine Schwierigkeit wurde auf ",
String templates should be used
```suggestion
      "setDiffTo1": "Deine Schwierigkeit wurde auf %s gesetzt",
```

2024-10-21 14:04 UTC, JonasFranke commented on src/main/resources/translations.json
> +      "setDiffTo2": " gesetzt",
```suggestion
```

2024-10-21 14:04 UTC, JonasFranke commented on src/main/resources/translations.json
> +      "setDiffOfTo1": "Die Schwierigkeit von ",
same here

2024-10-21 14:04 UTC, JonasFranke commented on src/main/resources/translations.json
> +      "loseMessage1": "Du hast verloren. Dein Inventar wird an deinem Todesort gedroppt",
same here

2024-10-21 14:04 UTC, JonasFranke commented on src/main/resources/translations.json
>    "en-US": [
Translations shall be added

2024-10-21 14:05 UTC, JonasFranke commented
When finished, the branch can be cleaned up with git rebase

2024-10-21 14:28 UTC, PrinzPizza42 commented on src/main/resources/translations.json
> +      "setDiffTo1": "Deine Schwierigkeit wurde auf ",
i split it like that because there parts of the message in between these two and those parts have diffferent styles, therefore I have to put them in differen text components

2024-10-21 14:36 UTC, PrinzPizza42 commented
just so i wont delete the code or something like that, what should i rebase and how? Should i rebase master on Settings-SetUp?

2024-10-21 14:36 UTC, PrinzPizza42 commented on .idea/gradle.xml
How do i remove the files from the commit?

2024-10-21 15:02 UTC, JonasFranke commented
> just so i wont delete the code or something like that, what should i rebase and how? Should i rebase master on Settings-SetUp?

Open the branch -> git rebase -i @~<Number of last commits on this branch, so 5> -> squash some changes -> save file

2024-10-21 18:54 UTC, JonasFranke commented on src/main/resources/translations.json
> +      "test": "This is a test %s",
```suggestion

```

2024-10-23 10:55 UTC, JonasFranke commented on .idea/gradle.xml
`git rm <FILENAME>` should do it

2024-10-23 12:17 UTC, PrinzPizza42 commented
ofcourse but can you tell me how to do that too? I’m not sure how i would do that

2024-10-23 12:18 UTC, JonasFranke commented
https://github.com/PrinzPizza42/DeathMinigames/pull/58#discussion_r1812483929

2024-10-23 12:20 UTC, PrinzPizza42 commented
is everything ready? If yes we could merge now

2024-10-23 12:35 UTC, JonasFranke requested changes
again some small changes

2024-10-23 12:35 UTC, JonasFranke commented on src/main/java/org/example/DeathMinigames/commands/GameCMD.java
>                      else {
Little nitpick: You're a bit inconsistent with your styling. Here the else is in the next line but in line 82 it's behind the bracket

2024-10-23 12:35 UTC, JonasFranke commented on src/main/java/org/example/DeathMinigames/listeners/InventoryListener.java
> +                // difficultyPlayerSettings
?

2024-10-23 12:35 UTC, JonasFranke commented on src/main/java/org/example/DeathMinigames/minigames/Difficulty.java
> +        return player.getInventory().contains(Material.DIAMOND, config.checkConfigInt("CostToLowerTheDifficulty"));
```suggestion
        Config config = new Config();
        return player.getInventory().contains(Material.DIAMOND, config.checkConfigInt("CostToLowerTheDifficulty"));
```

2024-10-23 12:35 UTC, JonasFranke commented on src/main/java/org/example/DeathMinigames/settings/GUI.java
> +        addClickableItemStack("back", Material.RED_CONCRETE, 1, 53);
Name is not a translation

2024-10-23 12:37 UTC, PrinzPizza42 commented on src/main/java/org/example/DeathMinigames/commands/GameCMD.java
>                      else {
i will change that later, normally im just putting the else in the next line

2024-10-23 12:38 UTC, PrinzPizza42 commented on src/main/java/org/example/DeathMinigames/listeners/InventoryListener.java
> +                // difficultyPlayerSettings
just a comment for me for orientation, i can delete them

2024-10-23 12:40 UTC, PrinzPizza42 commented on src/main/java/org/example/DeathMinigames/settings/GUI.java
> +        addClickableItemStack("back", Material.RED_CONCRETE, 1, 53);
i will add that later, thanks for looking at everything so closely

2024-10-23 13:15 UTC, JonasFranke commented on src/main/java/org/example/DeathMinigames/listeners/InventoryListener.java
> +                // difficultyPlayerSettings
I think this comment is not providing a benefit for readability. Removing would be better, I think

2024-10-23 15:34 UTC, merged